name: Unity - Activate
on: 
  workflow_dispatch:
  push:
  
jobs:
  build:
    name: UNIT TEST PROJECT
    runs-on: ubuntu-latest
    steps:
    # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
    #Cache
      - name: Cache
        uses: actions/cache@v2
        with:
          path: path/to/your/project/Library
          key: Library-MyProjectName-TargetPlatform
          restore-keys: |
            Library-MyProjectName-
            Library-
      - name: Tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
# Store Test Result
      - name: Store Test Result
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: ${{ steps.myTestStep.outputs.artifactsPath }}
#Code Coverage
      - name: Store Code Coverage 
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Coverage results
          path: ${{ steps.myTestStep.outputs.coveragePath }}
