name: Unity - Activate
on: 
  workflow_dispatch:
  push:
  
jobs:
  build:
    name: UNIT TEST PROJECT
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - playmode
    steps:
    # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
    #Cache
      - name: Cache
        uses: actions/cache@v2
        with:
          path: path/to/your/project/Library
          key: Library-MyProjectName-TargetPlatform
          restore-keys: |
            Library-MyProjectName-
            Library-
      #Test
      - name: Tests
        uses: game-ci/unity-test-runner@v2
        id: tests
        
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          checkName: ${{ matrix.testMode }} Test Results
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          #coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+my.assembly.*'
# Store Test Result
      - name: Store Test Result
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+my.assembly.*'
#Code Coverage
      - name: Store Code Coverage 
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Coverage results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.coveragePath }}
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+my.assembly.*'
          
